#!/bin/bash

if [ ! -d "/share/owntone" ]; then
  mkdir -p /share/owntone
fi

if [ ! -d "/share/owntone/dbase_and_logs" ]; then
  mkdir -p /share/owntone/dbase_and_logs
fi

if [ ! -d "/share/owntone/music" ]; then
  mkdir /share/owntone/music
fi

if [ ! -e "/share/owntone/owntone.conf" ]; then
  cp -f /etc/owntone.conf.orig /share/owntone/owntone.conf
fi

chown -R abc:abc /share/owntone/dbase_and_logs /share/owntone /share/owntone/music

# ugly part
cp /usr/share/owntone/htdocs/assets/index.js /usr/share/owntone/htdocs/assets/index_changed.js
sed -i -e "s/e=\"\/stream.mp3\"/e=\"stream.mp3\"/" /usr/share/owntone/htdocs/assets/index_changed.js
# ugly part - end


#chown abc:abc /var/log/owntone.log

IP=$(ifconfig eth0 | grep "inet addr:" | cut -d : -f 2 | cut -d " " -f 1)

OPTIONS_PATH=/data/options.json
CONFIG_PATH=/etc/owntone.conf

#cp -f /etc/owntone.conf.orig $CONFIG_PATH

#sed -i -e "/^#\?general {$/,/^#\?}$/s/^#\?\s*uid = .*/uid = \"abc\"/" $CONFIG_PATH
#sed -i -e "/^#\?general {$/,/^#\?}$/s/^#\?\s*logfile = .*/logfile = \"\/var\/log\/owntone.log\"/" $CONFIG_PATH

#sed -i -e "/^#\?general {$/,/^#\?}$/s/^#\?\s*db_path = .*/db_path = \"\/share\/owntone\/dbase_and_logs\/songs3.db\"/" $CONFIG_PATH

#sed -i -e "/^#\?general {$/,/^#\?}$/s/^#\?\s*bind_address = .*/bind_address = \"${IP}\"/" $CONFIG_PATH

# Change port for local nginx
#sed -i -e "/^#\?library {$/,/^#\?}$/s/^#\?\s*port = .*/port = 36890/" $CONFIG_PATH

cp -f /share/owntone/owntone.conf $CONFIG_PATH
