---
name: Owntone Server
version: latest
slug: owntone-server-beta
panel_icon: "mdi:cast-audio"
description: OwnTone is a Linux/FreeBSD DAAP (iTunes) media server with support for AirPlay devices, Apple Remote (and compatibles), MPD, Spotify, Chromecast, mp3 streaming and internet radio. It allows you to share your music collection over the local network.
arch:
  - armv7
  - aarch64
  - amd64
ports:
  3688/tcp: 3688
  6600/tcp: 6600
  5353/tcp: 5353
  3689/tcp: 3689
  3690/udp: 3690
  3691/udp: 3691
  36890/tcp: 36890

ports_description:
  3688/tcp: Websockets
  6600/tcp: MPD
  5353/tcp: Avahi
  3689/tcp: DAAP
  3690/udp: Control port - Airplay
  3691/udp: Timing port - Airplay
  36890/tcp: Nginx
map:
#  - config:rw
#  - media:rw
  - share:rw
host_network: false
full_access: false
host_dbus: false
host_ipc: false
ingress: true
hassio_api: false
auth_api: false
hassio_role: "default"
audio: true
ingress_port: 36890
webui: http://[HOST]:[PORT:36890]/
startup: application
boot: auto
stage: experimental
init: false
